package view;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                        
import javax.swing.JButton;
import javax.swing.JDialog;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                        
@SuppressWarnings("serial")                                                                                                                                                             
public class BuyDialog extends JDialog {                                                                                                                                               
                                                                                                                                                                                        
	private BuildPanel buildPanel;                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                      
	private JButton yesButton;                                                                                                                                                         
	private JButton returnButton;                                                                                                                                                       
                                                                                                                                                                                        
	public BuyDialog(PlayerActionPanel playerActionPanel) {                                                                                                                                                               
                                                                                                                                                                                        
		setUndecorated(true);                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                        
		buildPanel = new BuildPanel();                                                                                                                                                  
                                                                                                                                                                                        
		setContentPane(buildPanel);                                                                                                                                                     
                                                                                                                                                                                        
		pack();                                                                                                                                                                         
		setLocationRelativeTo(null);                                                                                                                                                    
                                                                                                                                                                                        
		setVisible(true);                                                                                                                                                               
		toFront();                                                                                                                                                                      
		requestFocus();                                                                                                                                                                 
                                                                                                                                                                                        
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                        
	public JButton getYesButton() {                                                                                                                                                    
		return yesButton;                                                                                                                                                              
	}                                                                                                                                                                                   
                                                                                                                                                                                        
	public JButton getReturnButton() {                                                                                                                                                  
		return returnButton;                                                                                                                                                            
	}                                                                                                                                                                                   
}                                                                                                                                                                                       
                                                                                                                                                                                        