package view;                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                 
import javax.swing.JButton;
import javax.swing.JPanel;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                        
@SuppressWarnings("serial")                                                                                                                                                             
public class BuyPanel extends JPanel {                                                                                                                                               
                                                                                                                                          
	private JButton yesButton;                                                                                                                                                         
	private JButton returnButton;                                                                                                                                                       
                                                                                                                                                                                        
	public BuyPanel() {                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                             
                                                                                                                                                                                           
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                        
	public JButton getYesButton() {                                                                                                                                                    
		return yesButton;                                                                                                                                                              
	}                                                                                                                                                                                   
                                                                                                                                                                                        
	public JButton getReturnButton() {                                                                                                                                                  
		return returnButton;                                                                                                                                                            
	}                                                                                                                                                                                   
}                                                                                                                                    